#5.1
countries = ['Япония','Америка','Россия','Таджикистан','Румыния']
print(countries)
print(sorted(countries))
print(countries)
print(sorted(countries, reverse=1))
print(countries)
countries.reverse() 
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=1)
print(countries)